#use_frameworks!

target 'BUKSocialKit_Example', :exclusive => true do
  pod 'BUKSocialKit', :path => '../'
end

target 'BUKSocialKit_Tests', :exclusive => true do
  pod 'BUKSocialKit', :path => '../'

  
end
